"""Serialization and parsing of omuq documents via xsdata.

The host SSP documents (SSD, SSV) are not handled here. They are edited
with lxml (see :mod:`omuq.xmlhost`), which preserves third-party content.
This module only handles the omuq instance documents themselves, which
omuq-python fully controls.
"""

from __future__ import annotations

import datetime as _dt

from xsdata.formats.dataclass.context import XmlContext
from xsdata.formats.dataclass.parsers import XmlParser
from xsdata.formats.dataclass.serializers import XmlSerializer
from xsdata.formats.dataclass.serializers.config import SerializerConfig
from xsdata.models.datatype import XmlDateTime

from .constants import GENERATION_TOOL, NSMAP
from .model import UncertaintyQuantification

_context = XmlContext()
_parser = XmlParser(context=_context)
_serializer = XmlSerializer(
    context=_context,
    config=SerializerConfig(
        indent="  ",
        xml_declaration=True,
        encoding="UTF-8",
        ignore_default_attributes=True,
    ),
)


def parse_study(data: bytes) -> UncertaintyQuantification:
    """Parse an omuq document from bytes."""
    return _parser.from_bytes(data, UncertaintyQuantification)


def serialize_study(doc: UncertaintyQuantification) -> bytes:
    """Serialize an omuq document to UTF-8 bytes with stable prefixes."""
    return _serializer.render(doc, ns_map=dict(NSMAP)).encode("utf-8")


def stamp_generation_info(
    doc: UncertaintyQuantification, *, refresh: bool = False
) -> None:
    """Fill ``generationTool``/``generationDateAndTime`` if not set by the user.

    These attributes come from the SSP ``ssc:ATopLevelMetaData`` attribute
    group reused by the omuq root element. Guideline section 4.5 asks
    writers to fill them when creating or modifying a document. With
    ``refresh=True`` (used by the write-back path in
    :mod:`omuq.writeback`) the timestamp is re-set unconditionally, so it
    records when the bytes were written. ``generationTool`` is only filled
    in when absent either way, so a document generated by another tool
    keeps that tool's name.
    """
    if doc.generation_tool is None:
        doc.generation_tool = GENERATION_TOOL
    if refresh or doc.generation_date_and_time is None:
        now = _dt.datetime.now(_dt.timezone.utc).replace(microsecond=0)
        doc.generation_date_and_time = XmlDateTime.from_datetime(now)
